Error: BUGFIX: Infinite type caused infinite loop
If there was an infinite type caused by a let expression, it would
cause the type checker to loop infinitely when trying to generalise
it. This commit adds a check in to check for cycles before
generalisation (just like for top level definitions).